[project]
name = "denv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Peled", email = "davidp.info1@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
denv = "denv:main"

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
